import Navbar from "../components/Navbar"
import './global.css'
export const metadata = {
  title: 'pokeAPI nextJS',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

 return (
    <html lang="es">
      <body>
        <header>
          <Navbar />
        </header>
        <main>
        {children}
        </main>
        
        <footer>
          <p>made with ❤️ by <a href="https://github.com/Maizo21">Maizo21</a></p>
        </footer>
        </body>
    </html>
  )
}
